name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: xhyrom/setup-bun@v0.1.8
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Build
        run: bun run build
